### ISSUE TITLE
supports_confidentiality? and :confidential? is not defined for doorkeper-sequel

### ISSUE THREAD

**Issue by byucesoy** [nbulaj/doorkeeper-sequel#11]
When I try to use `doorkeeper` with `doorkeeper-sequel`, `http://localhost:5000/oauth/applications/new` endpoint errors out saying;

```NoMethodError - undefined method `supports_confidentiality?' for Doorkeeper::Application:Class:```.

I checked the `doorkeeper-4.3.3/lib/doorkeeper/orm/active_record/application.rb` file and it implements those two functions however `doorkeeper-sequel-1.4.0/lib/doorkeeper/orm/sequel/application.rb` does not implement those functions.

I also added two dummy functions to `doorkeeper-sequel-1.4.0/lib/doorkeeper/orm/sequel/application.rb` and it seems to be working.

FYI, @nbulaj

**Comment by nbulaj** [comment]
Hi @byucesoy . You can produce a PR like it is done for doorkeeper-mongodb extension, take a look into

https://github.com/doorkeeper-gem/doorkeeper-mongodb/pull/32

**Comment by nbulaj** [comment]
Improved and released with 1.5.0 release, that requires Doorkeeper >= 4.2.6 (4.4.x suggested). Thanks!

**Comment by byucesoy** [comment]
Awesome, thanks for short response time.
