### ISSUE TITLE
:code_challenge does not inserted to DB

### ISSUE THREAD

**Issue by gencer** [nbulaj/doorkeeper-sequel#16]
I don't know actually if this is related to this gem or directly to the core (doorkeeper-gem) but here is what happens:

1. Client creates a request and fills `client_id`, `client_secret`, `code_challenge` and `code_challenge_type`.
2. Server asks user to approve this request/login. If accepts, gem creates a new row in the DB **without** `code_challenge` and `type`. So they are `NULL` variables.
3. Server returns authorization code and client asks for token with `code_verifier` parameter.
4. Request fails because verification is incorrect. Database says no code challenge but request send a verifier.

Now, I remove code challenge (pkce) in first request and auth as plain. It just works. Now let me try another path:

1. Client creates a request and fills `client_id`, `client_secret`.
2. Server asks user to approve this request/login. If accepts, gem creates a new row in the DB **without** `code_challenge` and `type`. So they are `NULL` variables. **Because we did not say we are going to use any challenge.**
3. Server returns successfully. Now we have tokens.
4. Create second request from client and this time add challenge.
5. Server accepts this token auth and insert challenge and type to DB.

As you can see, in the first place, doorkeeper does not insert code challenge and type to database.

I am using Sequel and this may be related to sequel support, however, im not sure.

Thanks,
Gencer.

**Comment by nbulaj** [comment]
Hi @gencer . Need to check if `code_challenge` is in the whitelisted fields

**Comment by nbulaj** [comment]
I tried to understand what is the source of this issue, but seems I don't full understand the issue :(

**Comment by gencer** [comment]
Hi @nbulaj. Basically, If a clients want to login first time (_no access token or approval before totally new user request_) `code_challenge` and `type` fields are not populated at first. But in second request (in this case user already allowed app and only token will be generated) then this fields are getting populated.

So at first authorization, `code_challenge` and `type` fields are not inserted to DB. After user allows and authorizes app, second and forthcoming requests successfully works with `code_challenge` and `type`

Is it working in your tests?

**Comment by gencer** [comment]
I no longer get this error. Will raise a new issue or re-open if I encounter again. Closing for now.
