### ISSUE TITLE
Rails 6 Support

### ISSUE THREAD

**Issue by farisj** [nbulaj/doorkeeper-sequel#21]
Hello,

I am wondering if this gem will officially support Rails 6? I see support for rails `5.0`, `5.1`, and `5.2` and am hoping to use this gem in a new Rails 6 project I am setting up.

Thanks so much for your time!

**Comment by gencer** [comment]
Rails 6 has no special treats. It just works. Problem is, Doorkeeper 5.1 and 5.2 is not supported by this gem. See ongoing PR #19. We need to update this gem first for `5.1.x` or `5.2.x` of doorkeeper.

**Comment by farisj** [comment]
Good to know, thanks for your response!

**Comment by gencer** [comment]
@farisj, I wanted to let you know that Rails 6.0 tests have been merged and Doorkeeper 5.2.x support <s>is on the way.</s> is on `master` now.

**Comment by nbulaj** [comment]
Already supports :tada:
