### ISSUE TITLE
Sequel5 support

### ISSUE THREAD

**Issue by gencer** [nbulaj/doorkeeper-sequel#5]
Is it possible to bring Sequel v5.x support to this gem?

~I manually changed gem version to 5.0 but I get an error like:
No database associated with Sequel::Model: have you called Sequel.connect or Sequel::Model.db= ? (Sequel::Error)
when generating migrations.~

Just making gem to set v5 will be enough. Previous error was a mistakenly my bad :)

**Comment by nbulaj** [comment]
Hi @gencer . So there are no problems with the Sequel5? Do I need to do smth?

**Comment by gencer** [comment]
@nbulaj, Only thing you have to do is increasing version in gemspec file. Currently, your gem does not installed without sequel v4. I have v5.

Here: https://github.com/nbulaj/doorkeeper-sequel/blob/master/doorkeeper-sequel.gemspec#L23

Also there is a problem with sequel+doorkeeper. Please have a look at #6.

**Comment by nbulaj** [comment]
Fixed and merged to `master`, you can try it out.
